In [1]:
import requests
import pandas as pd

In [29]:
r = requests.get('https://nba-stats-db.herokuapp.com/api/playerdata/season/2023')

In [30]:
df = pd.DataFrame(r.json()["results"])
df

,id,player_name,age,games,games_started,minutes_played,field_goals,field_attempts,field_percent,three_fg,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,team,season
0,1,Jalen Green,20,76,76,2602,566,1359,0.416,187,...,241,284,281,59,18,200,131,1683,HOU,2023
1,2,Jabari Smith Jr.,19,79,79,2451,364,892,0.408,120,...,447,569,101,43,74,104,227,1010,HOU,2023
2,3,Kenyon Martin Jr.,22,82,49,2292,410,720,0.569,68,...,326,452,123,41,30,91,147,1039,HOU,2023
3,4,Alperen Şengün,20,75,72,2171,442,799,0.553,19,...,436,678,291,70,70,193,258,1109,HOU,2023
4,5,Kevin Porter Jr.,22,59,59,2024,391,884,0.442,141,...,238,314,338,82,17,188,156,1130,HOU,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Nerlens Noel,28,3,1,43,1,6,0.167,0,...,6,9,3,3,1,5,7,3,BRK,2023
96,97,RaiQuan Gray,23,1,0,35,6,12,0.500,2,...,6,9,7,0,1,4,5,16,BRK,2023
97,98,Moses Brown,23,2,0,6,0,0,None,0,...,0,0,0,1,0,1,1,0,BRK,2023
98,99,Alondes Williams,23,1,0,5,0,0,None,0,...,1,1,0,0,0,2,1,0,BRK,2023
99,100,Scottie Barnes,21,77,76,2678,463,1016,0.456,63,...,333,512,371,83,61,154,170,1179,TOR,2023